services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: dap-app
    ports:
      - "8080:8080"
    environment:
      - SERVICE_SETTING_ENVIRONMENT=local
    networks:
      - dap-app-network
  db:    
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: dap-app-db
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/17/docker
      - POSTGRES_PASSWORD=test1234
    volumes:
      - dap-app-db:/var/lib/postgresql/17/docker
    networks:
      - dap-app-network      

volumes:
  dap-app-db:
    driver: local

networks:
  dap-app-network:
    driver: bridge