[project]
name = "dap-app-25-26"
version = "0.1.0"
description = "Example app for DAP-25-26"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "psycopg[binary]>=3.2.13",
    "pydantic-settings>=2.12.0",
]